### ISSUE TITLE
Don't set frame or stack-size via compiler commandline

### ISSUE THREAD

**Issue by cryptomilk** [darktable-org/rawspeed#211] opened 2019-12-30 10:08 UTC
Hi Roman,

I've talked to musl developers on IRC in #musl @ freenode about setting stack and frame size.

https://github.com/darktable-org/rawspeed/blob/develop/cmake/compiler-warnings.cmake#L16

This should be done using `pthread_attr_setstacksize()` if really needed for musl libc.

**Comment by LebedevRI** [comment] 2019-12-30 10:09
`-W<>` are *warning* flags, they do not actually set the limits.

**Comment by LebedevRI** [comment] 2019-12-30 21:01
To allow forward progress here, can you specify not *what* (current subj), but *why*?

**Comment by cryptomilk** [comment] 2019-12-31 12:45
You probably get warnings with this if you enable AddressSanitzer. It does some nasty things.

**Comment by LebedevRI** [comment] 2019-12-31 12:51
Please feel free to post coherent bugreport, if one exists and it's not a duplicate of #212.

**Closed as completed by LebedevRI** 2019-12-31 12:51 UTC
Labels: incomplete
