### ISSUE TITLE
DNG decoder doesn't decode black levels for RGB DNG files

### ISSUE THREAD

**Issue by madwyn** [darktable-org/rawspeed#233] opened 2020-05-20 16:45 UTC
In `DngDecoder.cpp`, function `bool DngDecoder::decodeBlackLevels(const TiffIFD* raw)`.

There is a test as below:
```C++
  if (mRaw->getCpp() != 1)
    return false;
```

This results the RGB DNG doesn't get the black levels stored in `50714 Black Level`, i.e. `blackLevel = -1` and `blackLevelSeparate` contains all zeros.

While LibRaw has correct behaviour to extract these values and store them in `cblack[]`.

Is this by design? Why?

BTW, thank you very much for developing this library, it's well designed, looks clean and easy to read.

**Comment by LebedevRI** [comment] 2020-05-20 16:47
Let's continue existing #215.
Duplicate of #215.

**Closed as completed by LebedevRI** 2020-05-20 16:47 UTC
