### ISSUE TITLE
Nikon Z9 raw is not supported in darktable

### ISSUE THREAD

**Issue by Tonywang0513** [darktable-org/rawspeed#383] opened 2022-09-13 14:11 UTC
The Nikon Z9 raw is not supported in darktable 4.0.  Z9 is a new mirrorless camera from Nikon with new format of raw.

**Comment by Tonywang0513** [comment] 2022-09-13 14:30
I have loaded one Z9 raw file via [https://raw.pixls.us/] according to Carlos Echenique.

**Comment by kmilos** [comment] 2022-09-14 08:42
Duplicate of #347 and https://github.com/darktable-org/darktable/issues/10889.

Please close, and search the existing issues before opening new ones.

**Closed as completed** 2022-11-18 19:21 UTC
