### ISSUE TITLE
Support the DJI Mavic 3 Pro

### ISSUE THREAD

**Issue by daniel-lucio** [darktable-org/rawspeed#746] opened 2024-08-31 02:43 UTC
Hi, besides this log I have, what information do you need to support this camera.

```
18,7230 [rawspeed] (DJI_20240830191157_0003_D.DNG) void rawspeed::AbstractDngDecompressor::decompress() const, line 249: Too many errors encountered. Giving up. First Error: 
virtual rawspeed::Buffer::size_type rawspeed::LJpegDecoder::decodeScan(), line 108: Unsupported predictor mode: 6 
    18,7230 [libraw_open] extensions whitelist: `cr3' 
    18,7230 [qoi_open] no proper file header in /mnt/vault/Photos/DJI/MAVIC 3 PRO/DJI_001/DJI_20240830191157_0003_D.DNG
```

**Comment by LebedevRI** [comment] 2024-08-31 02:51
Duplicate of https://github.com/darktable-org/rawspeed/issues/189.

**Closed as not planned by LebedevRI** 2024-08-31 02:51 UTC
