### ISSUE TITLE
z8 and z6 III support, access to raw.pixls.us ?

### ISSUE THREAD

**Issue by FTouzain** [darktable-org/rawspeed#764] opened 2024-11-24 22:18 UTC
Thank you for your work.

I read that to help supporting a camera, I may upload raw files (creative common licence) on [raw.pixls.us](http://raw.pixls.us/).
I would like to contribute but can reach this website.

Is there a new one? Otherwise may you provide me the procedure to follow to help in making you supporting those camera please? (just give a link if it is documented elsewhere)

Thank you in advance.
Fabrice

**Comment by kmilos** [comment] 2024-11-25 09:43
RPU is indeed down for a while unfortunately. Thanks for the offer, but I think there are samples for both models there before it went down...

Duplicate of https://github.com/darktable-org/darktable/issues/14593 (Z 8 is supported already)

Duplicate of https://github.com/darktable-org/darktable/issues/17075

Please follow up at issues above if you need to, or https://discuss.pixls.us/c/software/darktable/19. Note that the Nikon HE compression mode is not currently supported for any model, as the dt release notes clearly state.

**Closed as not planned** 2024-11-25 09:49 UTC
Labels: duplicate
