### ISSUE TITLE
DNG Converter DNGS: Please consider providing samples on <https://raw.pixls.us/>, thanks!

### ISSUE THREAD

**Issue by supertobi** [darktable-org/rawspeed#74] opened 2017-02-05 08:36 UTC
I converted a GoPro .gpr image with Adobe DNG Converter 9.8 to a .dng file. now I get this message from darktable:

> RawSpeed:Unable to find camera in database: 'GoPro' 'HERO5 Black' 'dng'
> Please consider providing samples on <https://raw.pixls.us/>, thanks!

As raw.pixls.us is  not interested in DNG files converted from Adobe DNG Converter, aren't you able to not show this message, if the DNGs are from the Adobe DNG Converter?

**Comment by axxel** [comment] 2017-02-05 09:25
@LebedevRI noticed this contradiction right after he introduced the message: #20 :). Simply has not come around to change it, I guess.

**Comment by LebedevRI** [comment] 2017-02-05 10:14
yes, what @axxel said :)
We should not ask for dng samples from ADC, and some other software (hdrmerge, dt)

**Comment by LebedevRI** [comment] 2017-02-05 10:14
Closing as duplicate of https://github.com/darktable-org/rawspeed/issues/20

**Closed as completed by LebedevRI** 2017-02-05 10:14 UTC
Labels: duplicate
