### ISSUE TITLE
This comparison operator is breaks weak ordering

### ISSUE THREAD

**Issue by Alexey-Danilchenko** [darktable-org/rawspeed#287] opened 2021-08-11 08:05 UTC
https://github.com/darktable-org/rawspeed/blob/4f03e0d42b1842f18b30a4e225e3bd39cbe00939/src/librawspeed/common/NORangesSet.h#L35

This comparison operator breaks weak ordering and on compilers with strict checking (GCC) breaks. It is quite understandable because for each a<b there also will be b<a so I am not sure how insering a buffer in a set will actually work for two non overlapping buffers. Specifically usage here breaking at runtime compiled with GCC and strict weak ordering checks:

https://github.com/darktable-org/rawspeed/blob/develop/src/librawspeed/tiff/TiffIFD.cpp?fbclid=IwAR3bEp2Hmm_Fj1ZbwDznU72_Nq23YNvnbNdOMFOoOgPIMqwLLauTYOpu3ew#L118

**Comment by LebedevRI** [comment] 2021-08-11 08:12
> Specifically usage here breaking at runtime compiled with GCC and strict weak ordering checks:

Which are enabled how?

Duplicate of #176

**Closed as completed by LebedevRI** 2021-08-11 08:12 UTC

**Comment by Alexey-Danilchenko** [comment] 2021-08-11 08:17
Enabled by default with libstdc++. How this works in clang - no idea.
