### ISSUE TITLE
add support for X-T5

### ISSUE THREAD

**Issue by andyczerwonka** [darktable-org/rawspeed#407] opened 2022-11-25 04:28 UTC
Please add support for the Fujifilm X-T5 lossless compressed.

**Comment by kmilos** [comment] 2022-11-25 07:59
Please search before opening new issues.

Duplicate of https://github.com/darktable-org/darktable/issues/12952 and https://github.com/darktable-org/rawspeed/pull/406

**Comment by LebedevRI** [comment] 2022-11-25 13:22
Duplicate of https://github.com/darktable-org/darktable/issues/12952

**Closed as completed by LebedevRI** 2022-11-25 13:22 UTC

**Comment by andyczerwonka** [comment] 2022-11-25 13:33
> Please search before opening new issues.
> 
> Duplicate of [darktable-org/darktable#12952](https://github.com/darktable-org/darktable/issues/12952) and #406

I did, but not the separate repository.
