### ISSUE TITLE
Sony ILCE-7M4 lossless compressed images not supported

### ISSUE THREAD

**Issue by LucasRueckert** [darktable-org/rawspeed#381] opened 2022-09-07 08:20 UTC
Hi,
I own a Sony ILCE-7M4 and I'd like to use the lossless compressed raw format.
In this issue [#12064](https://github.com/darktable-org/darktable/issues/12064) it was hinted that support in rawspeed was necessary.
I also uploaded some sample images to [raw.pixls.us](raw.pixls.us)

I'd like to help to get this working, so if somebody could point me to some documentation would be nice.

**Comment by lclevy** [comment] 2022-09-07 10:03
Hi, for your information, I started documenting Sony raw formats here: https://github.com/lclevy/sony_raw

**Comment by kmilos** [comment] 2022-09-07 11:50
Duplicate of https://github.com/darktable-org/rawspeed/issues/328, https://github.com/darktable-org/darktable/issues/10556 and https://github.com/darktable-org/darktable/issues/8523, please close, and continue discussion at the more appropriate, latter, place.

@lclevy The [Sony lossless format is understood](https://github.com/darktable-org/darktable/issues/8523#issuecomment-885688715) (4-channel JPEG SOF3).

**Comment by lclevy** [comment] 2022-09-07 11:58
@kmilos any reference, please?

**Comment by kmilos** [comment] 2022-09-07 11:59
I added the link to my original analysis, and [see also the PoC](https://github.com/darktable-org/darktable/issues/8523#issuecomment-1072793984) implemented by @cytrinox

**Comment by kmilos** [comment] 2022-09-07 12:18
@lclevy I'm not aware of any other "formal" reference when it comes to the Sony lossless mode - you can maybe as background point to the JPEG itu-t81.pdf spec itself for the SOF3 (LJPEG92) description and then to the Adobe DNG SDK for how it's used slightly differently in DNGs (2 channels instead of 4), also described here: https://thndl.com/how-dng-compresses-raw-data-with-lossless-jpeg92.html

**Comment by NickLplus** [comment] 2022-09-07 12:27
> @kmilos any reference, please?

Here is LibRaw implementation:
https://github.com/LibRaw/LibRaw/blob/master/src/decoders/decoders_libraw_dcrdefs.cpp#L75

**Comment by kmilos** [comment] 2022-09-07 12:41
Pretty please - close this and let's keep the discussion of this mode to one place: https://github.com/darktable-org/darktable/issues/8523

**Closed as not planned** 2022-09-08 10:01 UTC
